version: '3.5'
services:
  app: # NGINX
    build:
      context: .
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - '3002:80'

  dev:
    build:
      context: .
      target: builder
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run start
    ports:
      - '3002:3000'

  test-unit:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
