version: '3.5'
services:
  iot-frontend: # NGINX
    build:
      args:
        - BUILD_ENV=acc
      context: .
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - "3001:80"
  # networks_mode: "host"

  test-unit-integration:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
