version: '3.5'
services:
  app: # NGINX
    build:
      args:
        - BUILD_ENV=acc
      context: .
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - '3001:80'

  test-unit:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
