version: '3.5'
services:
  app: # NGINX
    build:
      context: .
      args:
        - REACT_APP_PIWIK_PRO_TRACKING_CODE=besttrackingcode
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - '3002:80'

  test-unit:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
